# Generated by Django 4.2.4 on 2023-08-09 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nebulaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workphoto',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('heading2', models.CharField(max_length=150, verbose_name='Подзаголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nebulaApp.workphoto', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
